name: bloomsay ci/cd

on:
  pull_request:
    branches: [pipfile-experiment]
  push:
    branches: [pipfile-experiment]
    tags:
      - 'v*.*.*'

jobs:
  build-and-test:
    name: build and test on python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      
      - name: python ${{ matrix.python-version }} setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
 
      - name: install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      
      - name: build package
        run: pipenv run python -m build
      
      - name: run pytests
        run: pipenv run pytest
      
      - name: store distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist-${{ matrix.python-version }}
          path: dist/

  publish-to-pypi:
    name: publish to PyPi
    needs: build-and-test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: download all dists
        uses: actions/download-artifact@v4
      
      - name: combine dists
        run: |
          mkdir dist
          find . -path '**/dist/*' -exec mv {} dist/ \;

      - name: publish bloomsay to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1