name: bloomsay ci/cd

on: 
  pull_request:
    branches: [pipfile-experiment]
  push:
    branches: [pipfile-experiment]

jobs: 
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      
      - name: python ${{ matrix.python-version }} setup 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      

      - name: install depencies 
        uses: kojoru/prepare-pipenv@v1
      
      - name: build package
        run: pipenv run python -m build
      
      - name: run pytests
        run: pipenv run pytest
      
      - name: store distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/

  publish-to-pypi:
    name: publish to test PyPi
    if: github.event_name == 'push' && github.ref == 'refs/heads/pipfile-experiment'
    needs: build-and-test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
    
    steps:
      - name: download dist files
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/
      
      - name: publish bloomsay to test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          repository-url: https://test.pypi.org/legacy/
          verbose: true

